In [1]:
import numpy as np

In [2]:
# Creating Numpy Array

In [3]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list)

In [5]:
type(x)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list(range(5))

[0, 1, 2, 3, 4]

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(3,4)

array([[0.13828024, 0.17784991, 0.15155483, 0.53692286],
       [0.36517337, 0.89609997, 0.22922354, 0.19339306],
       [0.3253755 , 0.19477713, 0.33606344, 0.39766863]])

In [17]:
np.random.randn(3,4)

array([[ 0.92153183, -0.30356629, -0.39858749, -0.49572622],
       [ 0.51836374,  0.31503867, -1.03488022,  0.76823897],
       [ 0.28737952,  1.80604581, -0.49010025, -0.0481977 ]])

In [18]:
np.random.randint(1,6)  # die

3

In [19]:
arr = np.arange(15)
ranarr = np.random.randint(0,50,10)

In [20]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr.shape

(15,)

In [23]:
arr.reshape(15,1).shape

(15, 1)

In [24]:
arr.dtype

dtype('int64')

In [25]:
ranarr

array([10, 30, 24, 16, 32,  0, 46, 25, 14, 35])

In [26]:
ranarr.max()

46

In [27]:
ranarr.argmax()  # returns index of max

6

In [28]:
ranarr.min()

0

In [29]:
ranarr.argmin()

5